#!/bin/bash

#SBATCH --job-name=gsm_sample_test
#SBATCH --partition=gpu_h100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=00:10:00
#SBATCH --output=outputs/gsm_sampletest_%A.out

echo "USING SMALL MODEL"
MODEL=meta-llama/Llama-3.2-1B-Instruct
EVAL_INSTANCES=10

#MODEL=meta-llama/Llama-3.1-8B-Instruct
#EVAL_INSTANCES=1000

NUM_BEAMS_LIST=1
NUM_RETURN_SEQUENCES=10
NUM_THREADS=4
TASK=gsm
SUITE=sample_${NUM_RETURN_SEQUENCES}_eval_${EVAL_INSTANCES}
./startup_job.ksh $TASK $MODEL $NUM_BEAMS_LIST $EVAL_INSTANCES $NUM_THREADS $SUITE
