echo "USING SMALL MODEL"
MODEL=meta-llama/Llama-3.2-1B-Instruct
EVAL_INSTANCES=2

#MODEL=meta-llama/Llama-3.1-8B-Instruct
#EVAL_INSTANCES=1000

NUM_BEAMS_LIST=1
NUM_RETURN_SEQUENCES=10
NUM_THREADS=4
TASK=gsm
export DISABLE_CACHE=true
#SUITE=sample_${NUM_RETURN_SEQUENCES}_eval_${EVAL_INSTANCES}


echo ./startup_job.ksh $TASK $MODEL $NUM_BEAMS_LIST $EVAL_INSTANCES $NUM_THREADS
./startup_job.ksh $TASK $MODEL $NUM_BEAMS_LIST $EVAL_INSTANCES $NUM_THREADS