#!/bin/bash

#SBATCH --job-name=beam2_1b
#SBATCH --partition=gpu_h100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=02:00:00
#SBATCH --output=outputs/test_inst_2_1b_%A.out

#MODEL=meta-llama/Llama-3.1-8B-Instruct
export MODEL=allenai/OLMo-2-1124-13B-Instruct
export NUM_BEAMS_LIST=2
export NUM_RETURN_SEQUENCES=1


export EVAL_INSTANCES=100
export TASK=instruct
export DISABLE_CACHE=false
export NUM_THREADS=4

export SUITE=full_instruct_${NUM_RETURN_SEQUENCES}_samples_${EVAL_INSTANCES}_evals
./startup_job.ksh $TASK $MODEL $NUM_BEAMS_LIST $EVAL_INSTANCES $NUM_THREADS $SUITE
