#!/bin/bash

#SBATCH --job-name=test_tokenizer
#SBATCH --output=outputs/test_tokenizer_%A.out
#SBATCH --partition=gpu_mig
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=00:30:00
source ~/miniconda3/bin/activate
conda activate crfm-helm2 

source hf.env
huggingface-cli login --token $HF_TOKEN --add-to-git-credential


echo huggingface-cli whoami
huggingface-cli whoami

./test_tokenizer.ksh
