#!/bin/bash

#SBATCH --job-name=wmt_100sample_llama7b
#SBATCH --partition=gpu_h100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=04:00:00
#SBATCH --output=outputs/wmt_100sample_llama7b_%A.out

export MODEL=meta-llama/Llama-3.1-8B-Instruct

export TASK=wmt
export NUM_BEAMS_LIST=1
export NUM_THREADS=2

export EVAL_INSTANCES=100
export NUM_RETURN_SEQUENCES=100
export SNELLIUS_METRICS="example_comet"
export SUITE="sample_return_${NUM_RETURN_SEQUENCES}_eval_${EVAL_INSTANCES}"
. ./startup_job.ksh $TASK $MODEL $NUM_BEAMS_LIST $EVAL_INSTANCES $NUM_THREADS $SUITE
