#!/bin/bash

#SBATCH --job-name=gsm_sample_test
#SBATCH --partition=gpu_h100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=03:00:00
#SBATCH --output=outputs/gsm_sample_%A.out

MODEL=meta-llama/Llama-3.2-1B-Instruct
EVAL_INSTANCES=1000

NUM_BEAMS_LIST=1
NUM_RETURN_SEQUENCES=10
NUM_THREADS=8
TASK=gsm
export DISABLE_CACHE=true


echo ./startup_job.ksh $TASK $MODEL $NUM_BEAMS_LIST $EVAL_INSTANCES $NUM_THREADS $NUM_RETURN_SEQUENCES
./startup_job.ksh $TASK $MODEL $NUM_BEAMS_LIST $EVAL_INSTANCES $NUM_THREADS $NUM_RETURN_SEQUENCES
