#!/bin/bash

#SBATCH --job-name=wmt_olmo_2b
#SBATCH --partition=gpu_h100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=03:00:00
#SBATCH --output=outputs/wmt_olmo_2beam_13b_%A.out

#MODEL=meta-llama/Llama-3.1-8B-Instruct
export MODEL=allenai/OLMo-2-1124-13B-Instruct
export NUM_BEAMS_LIST=2
export NUM_THREADS=32
export NUM_RETURN_SEQUENCES=1


export EVAL_INSTANCES=1000
export TASK=wmt
export DISABLE_CACHE=true

export SUITE=full_wmt_${NUM_RETURN_SEQUENCES}_samples_${EVAL_INSTANCES}_evals
./startup_job.ksh $TASK $MODEL $NUM_BEAMS_LIST $EVAL_INSTANCES $NUM_THREADS $SUITE
