#!/bin/bash

#SBATCH --job-name=beam2_8b
#SBATCH --partition=gpu_h100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=00:10:00
#SBATCH --output=outputs/test_beam2_8b_%A.out

export MODEL=meta-llama/Llama-3.1-8B-Instruct


export TASK=wmt
export EVAL_INSTANCES=5
export NUM_BEAMS_LIST=1
export NUM_THREADS=32
export NUM_RETURN_SEQUENCES=10
export POST_EXAMPLE_METRICS="comet"
export SUITE="sample_return_${NUM_RETURN_SEQUENCES}"
. ./startup_job.ksh $TASK $MODEL $NUM_BEAMS_LIST $EVAL_INSTANCES $NUM_THREADS $SUITE
